name: EPR
use_cuda: True
cuda_device_num: 0
logger: no_logger # [wandb, no_logger]
test_filename: data/tsp_100_test.pkl
# load_checkpoint: /home/lining/CVRP/EPR-master/TSP/weights
load_checkpoint:
training: joint # [joint, only_local]
lkh_file_path: '/home/lining/CVRP/EPR-master/TSP/data/lkh_costs.pt'
seed: 924
params:
  problem_size: 100
  scale_norm: True
  multiple_width: 100
  T: 300000
  mixed: False
  start_steps: 0
  train_steps: 350000
#  train_batch_size: 120
  train_batch_size: 80
  test_size: 10000
#  test_batch_size: 100
  test_batch_size: 60
  learning_rate: 0.0001
  log_step: 10000
  aug_factor: 8
distribution:
  data_type: uniform  # cluster, mixed, uniform, mix_three
  n_cluster: 3
  n_cluster_mix: 1
  lower: 0.2
  upper: 0.8
  std: 0.07
model_params:
  ensemble: True # [True, False]
  distance_penalty: True # [True, False]
  positional: True
  K: 20
  P: 0.1
  ensemble_size: 1
  xi: -1
  local_size: [30]
  euclidean: False
  embedding_dim: 128
  encoder_layer_num: 6
  head_num: 8
  qkv_dim: 16
  logit_clipping: 50
  ff_hidden_dim: 512
  local_att_hidden_dim: 32
  local_att_head_num: 4
  local_att_qkv_dim: 8